- platform: workday
  country: NL

- platform: template
  sensors:
    recentdoorbell:
      friendly_name: Doorbell rang
      value_template: '{{is_state("binary_sensor.doorbell", "on")}}'
      delay_off:
        minutes: 5

