- platform: ping
  host: 192.168.1.166
  name: "Nintendo Switch"
  count: 5
  scan_interval: 10

- platform: ping
  host: 192.168.1.75
  name: "Playstation 5"
  count: 5
  scan_interval: 10

- platform: workday
  country: NL

- platform: template
  sensors:
    recentdoorbell:
      friendly_name: Doorbell rang
      value_template: '{{is_state("binary_sensor.doorbell", "on")}}'
      delay_off:
        minutes: 5

