- platform: workday
  country: NL

- platform: template
  sensors:
    recentdoorbell:
      friendly_name: Doorbell rang
      value_template: '{{is_state("binary_sensor.doorbell", "on")}}'
      entity_id: binary_sensor.doorbell
      delay_off:
        minutes: 5

- platform: mqtt
  name: Doorbell
  state_topic: doorbell/binary_sensor/doorbell/state
  availability_topic: doorbell/status


