- platform: template
  sensors:
    studeerkamer_donker:
      value_template: '{{ (states.sensor.studeerkamer_illuminance.state | float(default=0) < 10) or ((states.sensor.studeerkamer_illuminance.state | float(default=0) < 30) and (states.light.zolder_kantoor.state == "on")) }}'
      friendly_name: 'Studeerkamer Donker'