- platform: template
  sensors:
    studeerkamer_donker:
      value_template: '{{ (states.sensor.studeerkamer_illuminance.state | float < 8) or ((states.sensor.studeerkamer_illuminance.state | float < 25) and (states.light.zolder_kantoor.state == "on")) }}'
      friendly_name: 'Studeerkamer Donker'