- id: '1613331598319'
  alias: Bak notificatie om half 9
  description: Om half 9 een trigger om te checken of de bak naar buiten moet
  trigger:
  - platform: time
    at: '20:30:01'
  condition: []
  action:
  - service: script.afvalbak_notificatie
    data: {}
  mode: single
- id: '1613681970688'
  alias: WC Light motion sensor
  description: Turns WC light on and off on the basis of Illuminance and motion
  use_blueprint:
    path: homeassistant/motion_light_illuminance.yaml
    input:
      light_brightness: '70'
      motion_entity: binary_sensor.wc
      light_target:
        entity_id: light.wc
      no_motion_wait: '3'
      illuminance_entity: sensor.illuminance_wc
      light_color_temperature: '400'
      high_illuminance_threshold: '40'
      turn_light_off: true
      low_illuminance_threshold: '20'
- id: '1637938739076'
  alias: Noud's kamer licht uit indien geen beweging
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 3978a19b701f4163ea44d277b358a148
    entity_id: binary_sensor.babykamer
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: b24c2edb85764923846a3bd10ebe9dbb
    entity_id: light.babykamer
    domain: light
  action:
  - type: turn_off
    device_id: b24c2edb85764923846a3bd10ebe9dbb
    entity_id: light.babykamer
    domain: light
  mode: single
- id: '1649147181462'
  alias: Firealarm Smoke detected
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: b62bd122651666f90d498e8be0a400e2
    entity_id: binary_sensor.rookmelder_keuken_smoke_alarm_smoke_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 408ea91b62274b73d8ab44479c40ec3f
    entity_id: binary_sensor.rookmelder_overloop_smoke_alarm_smoke_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 4eb3684153a1b21e7626084e60014a55
    entity_id: binary_sensor.rookmelder_zolder_smoke_alarm_smoke_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_iphone
    data:
      title: BRAND!
      message: Rookmelder gaat af
      data:
        push:
          sound:
            name: Alarm_Haptic.caf
            critical: 1
            volume: 1
  - service: notify.mobile_app_iphone_van_dionne
    data:
      title: BRAND!
      message: Rookmelder gaat af
      data:
        push:
          sound:
            name: Alarm_Haptic.caf
            critical: 1
            volume: 1
  mode: single
- id: '1664182591940'
  alias: Zolder slaapkamer licht aan/uit
  description: ''
  use_blueprint:
    path: homeassistant/motion_light_illuminance_v2.yaml
    input:
      motion_entity: binary_sensor.zolder_slaapkamer
      light_target:
        entity_id: light.zolder_slaapkamer
      no_motion_wait: 2
      illuminance_entity: sensor.lumi_lumi_sensor_motion_aq2_illuminance_2
      light_brightness: 60
      person_1: person.nik
      person_2: person.dionne
- id: '1664805697085'
  alias: Washok licht aan bij beweging
  description: ''
  use_blueprint:
    path: homeassistant/motion_light_illuminance_v2.yaml
    input:
      motion_entity: binary_sensor.washok
      light_target:
        entity_id: light.washok
      no_motion_wait: 0
      illuminance_entity: sensor.washok_licht
      light_brightness: 60
      person_1: person.nik
      person_2: person.dionne
      low_illuminance_threshold: 20
      high_illuminance_threshold: 40
- id: '1669235889542'
  alias: Fien kamer licht uit als er geen beweging is.
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 27d53bafbacc991083c9a75046ab0d34
    entity_id: binary_sensor.kleine_babykamer
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 75b5b78852b649a98c9acf3c095f37c3
    entity_id: light.kleine_babykamer
    domain: light
  action:
  - type: turn_off
    device_id: b409c71285f1a02f7fab03e079583728
    entity_id: light.strijkkamer
    domain: light
  mode: single
- id: '1669554831191'
  alias: Vitamines Fien
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.vitamines_gegeven
    from: 'off'
    to: 'on'
    id: gave_vitamines
  - platform: time
    at: 06:00:00
    id: reset
  - platform: state
    entity_id:
    - binary_sensor.woonkamer
    from: 'off'
    to: 'on'
    id: motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: motion
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.vitamines_gegeven
        state: 'off'
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'on'
          sequence:
          - service: light.turn_on
            data:
              color_name: mediumvioletred
            target:
              entity_id: light.keuken_1
        default:
        - service: light.turn_on
          data:
            color_name: mediumvioletred
            brightness: 255
          target:
            entity_id: light.keuken_1
      - condition: time
        before: 00:00:00
        after: '12:00:00'
      - service: light.turn_on
        data:
          flash: long
        target:
          entity_id: light.keuken_1
    - conditions:
      - condition: trigger
        id: gave_vitamines
      sequence:
      - alias: hoe kopieer ik de lamp
        choose:
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'off'
          sequence:
          - service: light.turn_off
            entity_id: light.keuken_1
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'on'
          sequence:
          - alias: Kopier lamp
            choose:
            - conditions:
                condition: state
                entity_id: light.keuken_5
                attribute: color_mode
                state: color_temp
              sequence:
              - service: light.turn_on
                entity_id: light.keuken_1
                data_template:
                  brightness: '{{state_attr("light.keuken_5", "brightness")}}'
                  color_temp: '{{state_attr("light.keuken_5", "color_temp")}}'
            - conditions:
                condition: state
                entity_id: light.keuken_5
                attribute: color_mode
                state: xy
              sequence:
                service: light.turn_on
                entity_id: light.keuken_1
                data_template:
                  brightness: '{{state_attr("light.keuken_5", "brightness")}}'
                  xy_color:
                  - '{{state_attr("light.keuken_5", "xy_color")[0]}}'
                  - '{{state_attr("light.keuken_5", "xy_color")[1]}}'
    - conditions:
      - condition: trigger
        id: reset
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.vitamines_gegeven
  mode: single
- id: '1669888891385'
  alias: Tag Nik is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 586b279f-53b3-4b96-9c9f-cc76963806b4
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: spotify:playlist:6woKGopyZEzZEO0Itmgwtp
      enqueue: play
    target:
      entity_id: media_player.studeerkamer
  mode: single
- id: '1670683085875'
  alias: plantjes water
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.plantjes_water
    from: 'off'
    to: 'on'
    id: water_gegeven
  - platform: time
    at: 06:00:00
    id: reset
  - platform: state
    entity_id:
    - binary_sensor.woonkamer
    from: 'off'
    to: 'on'
    id: motion
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: motion
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.plantjes_water
        state: 'off'
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'on'
          sequence:
          - service: light.turn_on
            data:
              color_name: green
            target:
              entity_id: light.keuken_2
        default:
        - service: light.turn_on
          data:
            color_name: green
            brightness: 255
          target:
            entity_id: light.keuken_2
      - condition: time
        weekday:
        - fri
        - thu
        - wed
        - tue
        - mon
        - sun
        before: 00:00:00
        after: 00:00:00
      - service: light.turn_on
        data:
          flash: long
        target:
          entity_id: light.keuken_2
    - conditions:
      - condition: trigger
        id: water_gegeven
      sequence:
      - alias: hoe kopieer ik de lamp
        choose:
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'off'
          sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.keuken_2
        - conditions:
          - condition: state
            entity_id: light.keuken_5
            state: 'on'
          sequence:
          - alias: Kopier lamp
            choose:
            - conditions:
                condition: state
                entity_id: light.keuken_5
                attribute: color_mode
                state: color_temp
              sequence:
              - service: light.turn_on
                entity_id: light.keuken_2
                data_template:
                  brightness: '{{state_attr("light.keuken_5", "brightness")}}'
                  color_temp: '{{state_attr("light.keuken_5", "color_temp")}}'
            - conditions:
                condition: state
                entity_id: light.keuken_5
                attribute: color_mode
                state: xy
              sequence:
              - service: light.turn_on
                entity_id: light.keuken_2
                data_template:
                  brightness: '{{state_attr("light.keuken_5", "brightness")}}'
                  xy_color:
                  - '{{state_attr("light.keuken_5", "xy_color")[0]}}'
                  - '{{state_attr("light.keuken_5", "xy_color")[1]}}'
    - conditions:
      - condition: trigger
        id: reset
      - condition: time
        weekday:
        - sat
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.plantjes_water
  mode: single
- id: '1673259984130'
  alias: Reset afvalbak lamp
  description: ''
  trigger:
  - platform: time
    at: 09:30:01
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.afval_vandaag
      state: Geen
  - condition: state
    entity_id: light.haldeur
    state: 'on'
  action:
  - service: script.copy_lamp
    data:
      source_lamp: light.bank
      target_lamp: light.haldeur
  mode: single
- id: '1673353448401'
  alias: Frigate notification front
  description: ''
  use_blueprint:
    path: hunterjm/frigate_0.10_notification.yaml
    input:
      camera: front
      base_url: !secret base_url
      notify_group: all_ios
      zones: {}
      labels:
      - person
- id: '1673365422069'
  alias: Frigate notification Back
  description: ''
  use_blueprint:
    path: hunterjm/frigate_0.10_notification.yaml
    input:
      camera: back
      base_url: !secret base_url
      notify_group: all_ios
- id: '1674039819138'
  alias: Schuur licht
  description: ''
  use_blueprint:
    path: homeassistant/motion_light_illuminance_v2.yaml
    input:
      motion_entity: binary_sensor.schuur
      no_motion_wait: 1
      light_target:
        entity_id: light.schuur
      illuminance_entity: sensor.schuur_illuminance
