homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longtitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  external_url: !secret base_url
  internal_url: http://192.168.1.15:8123
  allowlist_external_dirs:
    - /media/security
  country: NL

logger:
  default: warning

default_config:

person:

hassio:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

wake_on_lan:

# Store changes in InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 192.168.1.0/24
      #  trusted_networks:
      #    - !secret home_ip
  ip_ban_enabled: true
  #  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Recorder, keep 7 days in hass UI, rest is in grafana and influxDB
recorder:
  purge_keep_days: 7

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_merge_list sensor/

# Enables the ios component
ios:

# Text to speech
tts:
  - platform: google_translate
    language: 'nl'

# Cloud
#cloud:

light:
  - platform: switch
    name: Hal
    entity_id: switch.hal_verlichting
  # - platform: switch
  #   name: Kerstboom
  #   entity_id: switch.kerstboom
  # - platform: switch
  #   name: Kerstverlichting Achtertuin
  #   entity_id: switch.kerstverlichting_achtertuin
  - platform: group
    name: licht groep woonkamer
    entities:
      - light.woonkamer
      - light.keuken_dimmer

# remote:
#   - platform: xiaomi_miio
#     host: 192.168.1.21
#     token: !secret remote_token
#     commands:
#       soundbar_tv: 
#         command:
#           - raw:Z6VLADECAACDBgAAswgAAIMRAAAWIwAAMSMAAAidAAAAdwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAEBAQEAAQEBAAAAAAEBAQEBAQABAQAAAAAAAQAABgJXAkAA==
#       soundbar_music:
#         command:
#           - raw:Z6VLADICAACBBgAAsggAAIQRAAAeIwAACJ0AAAB3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAEBAQEAAQEBAAAAAAEAAQABAAABAAEAAQABAQABBQJGAkAA==
#       turn_on_tv:
#         command:
#           - raw:Z6VTAJ0BAADDAQAAbAMAAGgKAACwSQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjIQERIRIREREREBAREQERERIhEUEjIRERIRIREAEREQERERERERIgEQE=

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_security_chat_id
      - !secret telegram_notification_chat_id
      - !secret telegram_dionne_chat_id

#Setting up notifications
notify:
  - name: Nik telegram
    platform: telegram
    chat_id: !secret telegram_chat_id
  - name: Security telegram
    platform: telegram
    chat_id: !secret telegram_security_chat_id
  - name: all ios
    platform: group
    services:
      - service: mobile_app_iphone_van_nik
      - service: mobile_app_iphone_van_dionne

# Z-wave
# zwave:
#   usb_path: /dev/ttyACM0
#   device_config: !include zwave_device_config.yaml

stream:

alarm_control_panel:
  - platform: manual
    code: !secret alarm_control_panel_code
    name: Home alarm
    trigger_time: 60
    arming_time: 0
    delay_time: 0

zone: !include zones.yaml
input_select: !include input_select.yaml
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include input_number.yaml
binary_sensor: !include_dir_merge_list binary_sensor/
group: !include_dir_merge_named group/
automation old: !include_dir_merge_list automation/
automation: !include automations.yaml
script: !include_dir_merge_named scripts/
script ui: !include scripts.yaml
switch: !include switch.yaml
template: !include_dir_merge_list template/