version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /tmp/:/tmp/
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host