- platform: template
  sensors:
    alarm_time:
      friendly_name: Wekker
      value_template: >
        {%-if states.input_number.alarm_hour.state|int|string|length == 1-%}
        0
        {%-endif-%}
        {{states.input_number.alarm_hour.state | int-}}
        :
        {%-if states.input_number.alarm_minute.state|int|string|length == 1-%}
        0
        {%-endif-%}
        {{states.input_number.alarm_minute.state | int}}
      icon_template: mdi:alarm
      entity_id:
        - input_number.alarm_hour
        - input_number.alarm_minute
    alarm_fade:
      friendly_name: Start fade-in
      value_template: >
        {%-if states.input_number.alarm_minute.state | int < states.input_number.alarm_fade.state|int-%}
        {%-if (states.input_number.alarm_hour.state | int -1)|string|length == 1-%}
        0
        {%-endif-%}
        {{states.input_number.alarm_hour.state | int -1}}
        {%-else-%}
        {%-if states.input_number.alarm_hour.state|int|string|length == 1-%}
        0
        {%-endif-%}
        {{states.input_number.alarm_hour.state | int}}
        {%-endif-%}
        :
        {%- if states.input_number.alarm_minute.state|int < states.input_number.alarm_fade.state|int-%}
        {{states.input_number.alarm_minute.state | int + (60 -states.input_number.alarm_fade.state|int)}}
        {%-else-%}
        {%-if (states.input_number.alarm_minute.state|int - states.input_number.alarm_fade.state|int)|string|length == 1-%}
        0
        {%-endif-%}
        {{states.input_number.alarm_minute.state | int - states.input_number.alarm_fade.state|int}}
        {%-endif-%}
      icon_template: mdi:weather-sunset
      entity_id:
        - input_number.alarm_hour
        - input_number.alarm_minute
        - input_number.alarm_fade
