- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Temperature"  
  unit_of_measurement: "째F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt  
  state_topic: "bruh/sensornode2"  
  name: "SN2 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt  
  state_topic: "bruh/sensornode2"  
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "bruh/sensornode2"  
  name: "SN2 Temperature"  
  unit_of_measurement: "째F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "SN2 Real Feel"
  unit_of_measurement: "째F"
  value_template: '{{ value_json.heatIndex | round(1) }}'