- platform: yr

- platform: time_date
  display_options:
    - 'time'

#- platform: zoneminder

- platform: hvc
  postalcode: !secret postalcode
  housenumber: !secret housenumber

- platform: postnl
  username: !secret postnl_username
  password: !secret postnl_password

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    