- platform: time_date
  display_options:
    - 'time'

#- platform: zoneminder

- platform: hvc
  postalcode: !secret postalcode
  housenumber: !secret housenumber

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    
- platform: dnsip