- platform: waze_travel_time
  name: Nik to Home
  origin: person.nik
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: Dionne to Home
  origin: person.dionne
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: Nik to Work
  origin: person.nik
  destination: zone.kpn_zoetermeer
  region: 'EU'

- platform: waze_travel_time
  name: Dionne to Work
  origin: person.dionne
  destination: zone.kindergarden_haarlem
  region: 'EU'