- alias: Centrale ventilatie hoog indien vochtig in badkamer
  trigger:
    platform: numeric_state
    entity_id: sensor.badkamer_vochtigheid
    above: 80
  action: 
    service: switch.turn_on
    entity_id:
      - switch.ventilatie_hoog

- alias: Centrale ventilatie uit indien badkamer niet meer vochtig is
  trigger:
    - platform: numeric_state
      entity_id: sensor.badkamer_vochtigheid
      below: 65
    - platform: numeric_state
      entity_id: sensor.badkamer_vochtigheid
      below: 80
      for:
        hours: 1
    - platform: state
      entity_id: switch.ventilatie_hoog
      to: 'on'
      for:
        hours: 1
        minutes: 30
  action: 
    service: switch.turn_off
    entity_id:
      - switch.ventilatie_hoog

- alias: badkamer licht aan bij beweging
  id: badkamer_licht_aan
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer2
      from: 'off'
      to: 'on'
  action:
    - alias: "Only trigger when lights are off"
      condition: state
      entity_id: light.badkamer
      state: "off"
    - alias: "When sleeping, dim lights"
      choose:
      - conditions:
          condition: and
          conditions:
            - condition: state
              entity_id: group.wakker
              state: 'off'
            - condition: time
              before: '06:00:00'
              after: '23:00:00'
        sequence:
          - alias: "dim lights badkmaer"
            service: hue.hue_activate_scene
            data:
              group_name: Badkamer
              scene_name: Nachtlampje
      default:
        - alias: "turn on light normally"
          service: hue.hue_activate_scene
          data:
            group_name: Badkamer
            scene_name: Lezen

- alias: badkamer licht uit geen beweging
  id: badkamer_licht_uit
  trigger:
    - platform: state
      id: douchen
      entity_id: binary_sensor.badkamer2
      from: 'on'
      to: 'off'
      for:
        minutes: 9
    - platform: state
      id: niet_douchen
      entity_id: binary_sensor.badkamer2
      from: "on"
      to: "off"
      for:
        minutes: 2
  action:
    - alias: depending if someone showers turn of after 2 or 9 minutes
      choose:
      - conditions:
        - alias: "There is no one showering"
          condition: state
          entity_id: binary_sensor.douchen
          state: "off"
        sequence:
          - alias: "turn off light"
            service: light.turn_off
            target:
              entity_id: light.badkamer
      - conditions:
          - condition: trigger
            id: douchen
        sequence:
          - alias: "turn off light"
            service: light.turn_off
            target:
              entity_id: light.badkamer