- alias: Centrale ventilatie hoog indien vochtig in badkamer
  trigger:
    platform: numeric_state
    entity_id: sensor.badkamer_vochtigheid
    above: 80
  action: 
    service: switch.turn_on
    entity_id:
      - switch.ventilatie_hoog

- alias: Centrale ventilatie uit indien badkamer niet meer vochtig is
  trigger:
    - platform: numeric_state
      entity_id: sensor.badkamer_vochtigheid
      below: 65
    - platform: numeric_state
      entity_id: sensor.badkamer_vochtigheid
      below: 80
      for:
        hours: 1
    - platform: state
      entity_id: switch.ventilatie_hoog
      to: 'on'
      for:
        hours: 1
        minutes: 30
  action: 
    service: switch.turn_off
    entity_id:
      - switch.ventilatie_hoog

- alias: badkamer licht aan bij beweging
  id: badkamer_licht_aan
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer2
      from: 'off'
      to: 'on'
  action:
    - alias: "When sleeping, dim lights "
      choose:
      - conditions:
          condition: and
          conditions:
            - condition: state
              entity_id: group.wakker
              state: 'off'
            - condition: time
              before: '06:00:00'
              after: '23:00:00'
        sequence:
          - alias: "dim lights badkmaer"
            service: hue.hue_activate_scene
            data:
              group_name: Badkamer
              scene_name: Nachtlampje
      default:
        - alias: "turn on light normally"
          service: hue.hue_activate_scene
          data:
            group_name: Badkamer
            scene_name: Lezen

- alias: badkamer licht uit geen beweging
  id: badkamer_licht_uit
  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer2
      from: 'on'
      to: 'off'
      for:
        minutes: 9
  action:
    service: light.turn_off
    entity_id: light.badkamer