- alias: Muziek strijkkamer aan
  trigger:
    platform: state
    entity_id: binary_sensor.beweging_strijkkamer
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{(states.media_player.strijkkamer.state) != ('playing')}}"
      - condition: state
        entity_id: input_boolean.nik_wakker
        state: 'on'
      - condition: state
        entity_id: input_boolean.dionne_wakker
        state: 'on'
      - condition: state
        entity_id: media_player.woonkamer
        state: 'playing'
      - condition: template
        value_template: '{{states.media_player.strijkkamer.attributes.sonos_group[0] != "media_player.woonkamer"}}'
  action:
    - service: media_player.volume_set
      entity_id: media_player.strijkkamer
      data:
        volume_level: 0.05
    - service: sonos.join
      entity_id: media_player.strijkkamer
      data:
        master: media_player.woonkamer

- alias: Muziek strijkkamer uit
  trigger:
    platform: state
    entity_id: binary_sensor.beweging_strijkkamer
    to: 'off'
    for:
      minutes: 15
  condition:
    condition: template
    value_template: '{{states.media_player.strijkkamer.attributes.sonos_group[0] == "media_player.woonkamer"}}'
  action:
    - service: sonos.unjoin
      entity_id: media_player.strijkkamer

- alias: Muziek slaapkamer aan
  trigger:
    platform: state
    entity_id: binary_sensor.slaapkamer
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{states.media_player.grote_slaapkamer.state == null
          or 
          states.media_player.grote_slaapkamer.state == 'unavailable'}}
      - condition: template
        value_template: "{{(states.media_player.slaapkamer.state) != ('playing')}}"
      - condition: state
        entity_id: input_boolean.nik_wakker
        state: 'on'
      - condition: state
        entity_id: input_boolean.dionne_wakker
        state: 'on'
      - condition: state
        entity_id: media_player.woonkamer
        state: 'playing'
      - condition: template
        value_template: '{{states.media_player.slaapkamer.attributes.sonos_group[0] != "media_player.woonkamer"}}'
  action:
    - service: media_player.volume_set
      entity_id: media_player.slaapkamer
      data:
        volume_level: 0.10
    - service: sonos.join
      entity_id: media_player.slaapkamer
      data:
        master: media_player.woonkamer

- alias: Muziek slaapkamer uit
  trigger:
    - platform: state
      entity_id: binary_sensor.slaapkamer
      to: 'off'
      for:
        minutes: 15
    - platform: state
      entity_id: media_player.grote_slaapkamer
      from: 'unavailable'
  action:
    - choose:
        # IF player is grouped
        - conditions:
            - condition: template
              value_template: '{{states.media_player.slaapkamer.attributes.sonos_group[0] == "media_player.woonkamer"}}'
          sequence:
            - service: sonos.unjoin
              entity_id: media_player.slaapkamer
      # ELSE (Player not grouped)
      default:
        - service: media_player.media_pause
          entity_id: media_player.slaapkamer

- alias: Muziek boven uit als iemand gaat slapen
  trigger:
    - platform: state
      entity_id:
        - input_boolean.nik_wakker
        - input_boolean.dionne_wakker
      to: 'off'
  condition:
    condition: state
    entity_id: group.wakker
    state: 'on'
  action:
    - service: sonos.unjoin
      entity_id: media_player.strijkkamer
    - service: sonos.unjoin
      entity_id: media_player.slaapkamer
    - delay:
        seconds: 2
    - service: media_player.media_stop
      entity_id:
        - media_player.strijkkamer
        - media_player.slaapkamer