- alias: Homeassistant start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.ios_nik
      data:
        title: 'Homeassistant start'
        message: 'Homeassistant start'

- alias: Homeassistant stopt
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.ios_nik
      data:
        title: 'Homeassistant stopt'
        message: 'Homeassistant stopt'
        