- alias: Homeassistant start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.mobile_app_iphone_van_nik
      data:
        title: 'Homeassistant start'
        message: 'Homeassistant start'

- alias: Homeassistant stopt
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.mobile_app_iphone_van_nik
      data:
        title: 'Homeassistant stopt'
        message: 'Homeassistant stopt'
        
- alias: IP changed
  trigger:
    platform: state
    entity_id: sensor.myip
  action:
    - service: notify.nik_telegram
      data:
        title: 'Thuis IP veranderd'
      data_template:
        message: 'Het ip is veranderd van {{trigger.from_state.state}} to {{trigger.to_state.state}}'
