- alias: Statping server offline
  id: statping
  trigger:
    platform: webhook
    webhook_id: !secret statping_webhook
  action:
    service: notify.nik_telegram
    data:
      message: "{{trigger.json.name}} is {{trigger.json.status}}"