- alias: beweging strijkkamer
  trigger:
    platform: state
    entity_id: binary_sensor.beweging_strijkkamer
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.sn2_ldr
    above: 350
  action:
    service: light.turn_on
    entity_id: light.strijkkamer

- alias: geen beweging strijkkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.beweging_strijkkamer
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.sn2_ldr
      below: 250
  action:
    service: light.turn_off
    entity_id: light.strijkkamer

- alias: Led strijkkamer aan
  trigger:
    platform: 'state'
    entity_id: binary_sensor.beweging_strijkkamer
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.sn2_led
    data_template:
      rgb_color: ['{{ range(0, 255) | random | int}}','{{ range(0, 255) | random | int }}','{{ range(0, 255) | random | int }}']

- alias: Led strijkkamer uit
  trigger:
    platform: 'state'
    entity_id: binary_sensor.beweging_strijkkamer
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.sn2_led