- alias: beweging studeerkamer
  id: beweging studeerkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.studeerkamer
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.studeerkamer_donker
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.studeerkamer_donker
      state: 'on'
    - condition: state
      entity_id: binary_sensor.studeerkamer
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.zolder_kantoor

- alias: geen beweging studeerkamer
  id: geen_beweging_studeerkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.studeerkamer
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.studeerkamer_donker
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.monitor_on
      from: "on"
      to: "off"
      for:
        minutes: 5
  condition:
  - condition: not
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.monitor_on
            state: 'on'
          - condition: state
            entity_id: binary_sensor.studeerkamer_donker
            state: 'on'
  action:
    service: light.turn_off
    entity_id: light.zolder_kantoor