- alias: beweging studeerkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.studeerkamer
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.studeerkamer_donker
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.studeerkamer_donker
      state: 'on'
    - condition: state
      entity_id: binary_sensor.studeerkamer
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.zolder_kantoor

- alias: geen beweging studeerkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.studeerkamer
      from: 'on'
      to: 'off'
      for:
        minutes: 15
    - platform: state
      entity_id: binary_sensor.studeerkamer_donker
      from: 'on'
      to: 'off'
  condition:
  - condition: not
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.niks_macbook_pro_active
            state: 'on'
          - condition: state
            entity_id: device_tracker.niks_mbp_wifi
            attribute: ap_mac
            state: 'e0:63:da:ac:35:75'
  action:
    service: light.turn_off
    entity_id: light.zolder_kantoor