# - alias: media player control
#   trigger:
- alias: reset robbie
  trigger:
    platform: time
    at: '04:59:00'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.robbie


